{{- if .Values.appSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "id-generator.fullname" . }}-secret
  namespace: {{ include "id-generator.namespace" . }}
  labels:
    {{- include "id-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.appSecret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
