apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  namespace: ramos-id-generator-test
  labels:
    app.kubernetes.io/part-of: valkey-sentinel
data:
  master.conf: |
    port 6379
    requirepass testpass
    masterauth testpass
    appendonly yes
    appendfsync everysec

  replica.conf: |
    port 6379
    requirepass testpass
    masterauth testpass
    replicaof valkey-master.ramos-id-generator-test.svc.cluster.local 6379
    appendonly yes
    appendfsync everysec

  sentinel.conf: |
    port 26379
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel monitor mymaster valkey-master.ramos-id-generator-test.svc.cluster.local 6379 2
    sentinel auth-pass mymaster testpass
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1
