apiVersion: v1
kind: Service
metadata:
  name: valkey-master
  namespace: ramos-id-generator-test
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/component: master
    app.kubernetes.io/part-of: valkey-sentinel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/component: master
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      protocol: TCP
