{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
