spring:
  application:
    name: id-generator
  profiles:
    default: local
    group:
      local: jpa-local, valkey-local
      alpha: jpa-alpha, valkey-alpha
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: when-authorized
